Repository nasa/ci_lab, pull requests merged in 2020-11, with the labels that each got.

#58 Fix #57, Use MSG APIs
  fsw/src/ci_lab_app.c
  fsw/src/ci_lab_app.h
  fsw/src/ci_lab_msg.h
Labels: CCB-20201104, CCB-READY, IC-20201110

#61 Fix #59, Remove non-portable OS_PACK
  fsw/src/ci_lab_msg.h
Labels: CCB - Fast Track, IC-20201110

#60 Integration Candidate 2020-11-10
  README.md
  fsw/src/ci_lab_app.c
  fsw/src/ci_lab_app.h
  fsw/src/ci_lab_msg.h
  fsw/src/ci_lab_version.h
Labels: IC-20201110
