Repository nasa/ci_lab, pull requests merged in 2021-03, with the labels that each got.

#75 Fix #74, Add Testing Tools to the Security Policy
  SECURITY.md
Labels: CCB:FastTrack, docs

#78 Fix #77, use cfe.h instead of individual headers
  fsw/src/ci_lab_app.h
Labels: CCB:FastTrack

#81 Fix #80, Add Contributing Guide
  CONTRIBUTING.md
Labels: CCB:FastTrack, docs

#83 Fix #82, remove app registration
  fsw/src/ci_lab_app.c
Labels: CCB:FastTrack

#84 Fix #73, use zero copy API
  fsw/src/ci_lab_app.c
  fsw/src/ci_lab_events.h
Labels: IC:2021-03-30
